Replace realpath with Path.expand
membraneframework/bundlex pull request #125
Opened 2024-03-01 16:48 UTC by mickel8

`realpath` might not be installed on some OSes. I wonder if we could just use `Path.expand` instead, like in the PR?

2024-03-06 11:08 UTC, FelonEkonom commented on lib/bundlex/toolchain/common/unix/os_deps.ex
> +    physical_output_path = logical_output_path |> Path.expand() |> String.trim_trailing()
```suggestion
{physical_output_path, 0} = 
  try do
   System.cmd("realpath", ["logical_output_path"])
  rescue
    e in ErlangError -> 
      with %{original: :enoent} <- e do
        Logger.error("realpath is required by Bundlex, but it is not installed")
      end
      
      reraise e, __STACKTRACE__
    end    
    
  physical_output_path = String.trim_trailing(physical_output_path)
```
Is it ok for you?

2024-03-06 11:23 UTC, mickel8 commented on lib/bundlex/toolchain/common/unix/os_deps.ex
> +    physical_output_path = logical_output_path |> Path.expand() |> String.trim_trailing()
It's for sure better! :)

2024-03-15 11:40 UTC, mat-hek requested changes
Since it seems that the lack of `realpath` is the only thing that currently prevents Bundlex from working on a clean Mac OS, I'd instead use `:file.read_link`. Since it works only for symlinks, it would probably require having `Bundlex.Toolchain.real_output_path` that would check if `priv` is a symlink and resolve it's real path in that case.

2024-04-04 12:45 UTC, mat-hek commented
@mickel8 it should work without `realpath` now, can you check?

2024-04-09 09:49 UTC, FelonEkonom approved these changes

2024-04-09 09:49 UTC, FelonEkonom commented on test/bundlex/integration_test.exs
> +  Enum.map([false, true], fn priv ->
```suggestion
  Enum.map([false, true], fn priv? ->
```

2024-04-15 14:54 UTC, mickel8 commented
It works, the only things is taht `/bin/sh: realpath: command not found` is printed

2024-04-17 15:41 UTC, mat-hek approved these changes

2024-04-17 15:41 UTC, merged